### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by chrisdothtml** [dynasticdevelop/place#10]
I have quite a bit of experience maintaining projects and repos, and have a few notes:

### 1. Code style

> Please follow the coding styles throughout the project

isn't going to do when you have multiple people contributing. You need to decide on a linting tool/style framework and enforce it as part of the build or test process (I use StandardJS).

### 2. Yarn

[Use it](https://yarnpkg.com/en/). Much faster and more reliable than npm

### 3. Dependency Management

Dependencies can get out of hand quickly. It's always best to introduce a new dependency only when you **need** to. Obviously frameworks, etc. are inevitable, but try to be frugal with adding new dependencies; and always remove dependencies if they're not used anymore

### 4. CI

Travis checks and / or tests?

I'm willing to PR with some/all of these updates, but they should be agreed on beforehand

**Comment by AppleBetas** [comment]
Once we're ready for launch we'll look into these more

**Comment by itsmehemant123** [comment]
👍🏻

**Comment by nullpixel** [comment]
Joel#7453 is working on reworking clientside js, and is adding things like an eslint config. Once this is done, I will write up a set of guidelines.

**Comment by nullpixel** [comment]
Took me a while to get this out, but it's here!
