### ISSUE TITLE
Pixel placement not lining up properly with the board

### ISSUE THREAD

**Issue by Alex1331xela** [dynasticdevelop/place#121]
Neither pixel placement nor the grid is lining up with what I'm seeing. When I try to place a pixel, it places two or three spots to the right

Using Windows 7, Chrome browser

![image](https://cloud.githubusercontent.com/assets/13511957/25732803/4e406cce-3121-11e7-90b3-2ae4d17d4be5.png)

**Comment by AppleBetas** [comment]
Are you zoomed in when this happens?

**Comment by Alex1331xela** [comment]
With my browser? Not zoomed in, no

**Comment by AppleBetas** [comment]
Can you clear your browser cache and try again?

**Comment by Alex1331xela** [comment]
The problem persists even after clearing browser cache

**Comment by AppleBetas** [comment]
Cannot reproduce on many different browser and OS combinations. Please check to see if you have any settings that would affect font sizes, DPI, scale, or related settings so that I can narrow this down

**Comment by Alex1331xela** [comment]
I don't have any settings that would affect that. If it helps, I do have 1920x1200 screen resolution, which I believe is considered "high DPI". The issue has happened all of a sudden though, without any settings changes by me

**Comment by Alex1331xela** [comment]
My issue is resolved, I had to clear cache including hosted app data. Thank you for the help AppleBetas
