### ISSUE TITLE
Error in util/PaintingHandler.js:110

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#122]
## Error in Place 2.0

**Error** in **util/PaintingHandler.js:110**
Batch is already running

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590c016fd8fcda0018de125e&i=gh&m=ci)

## Stacktrace

    util/PaintingHandler.js:110 - addPixel
    models/user.js:182 - none

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590c016fd8fcda0018de125e&i=gh&m=ci)

**Comment by AppleBetas** [comment]
Duplicate of #63

**Comment by nullpixel** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590f7fcbcee08400187558a6&i=gh&m=ra)

**Comment by AppleBetas** [comment]
Duplicate of #63

**Comment by nullpixel** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=5910d19e51897a0018a63eba&i=gh&m=ra)

**Comment by nullpixel** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=59138ea51d6f56001a99c60f&i=gh&m=ra)

**Comment by nullpixel** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=591507c6092ddd0019338e3a&i=gh&m=ra)

**Comment by AppleBetas** [comment]
Merged with #143 because line number changed and BugSnag is too stupid to realize that
