### ISSUE TITLE
Error in app.js:112

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#127]
## Error in Place 2.0

**Error** in **app.js:112**
listen EADDRINUSE :::3000

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590f7dd2a585bb00194bf839?event_id=590f7dd2a585bb00194bf838&i=gh&m=ci)

## Stacktrace

    app.js:112 - none

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590f7dd2a585bb00194bf839?event_id=590f7dd2a585bb00194bf838&i=gh&m=ci)

**Comment by AppleBetas** [comment]
shut the fuck up you're not bugsnag you're nobugsnag
