### ISSUE TITLE
Error in /api/place

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#128]
## Error in Place 2.0

**Error** in **/api/place**
request aborted

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590f977e8261340019f1af81?event_id=590f977e8261340019f1af80&i=gh&m=ci)

## Stacktrace

    node_modules/raw-body/index.js:269 - onAborted

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590f977e8261340019f1af81?event_id=590f977e8261340019f1af80&i=gh&m=ci)

**Comment by AppleBetas** [comment]
Not a bug
