### ISSUE TITLE
Simultaneous paint requests fail (util/PaintingHandler.js:111)

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#143]
## Error in Place 2.0

**Error** in **util/PaintingHandler.js:111**
Batch is already running

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/591badc94390bb001b42dda3?event_id=591badc94390bb001b42dda2&i=gh&m=ci)

## Stacktrace

    util/PaintingHandler.js:111 - addPixel
    models/user.js:189 - none

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/591badc94390bb001b42dda3?event_id=591badc94390bb001b42dda2&i=gh&m=ci)

**Comment by AppleBetas** [comment]
Moved to #163 because Bugsnag is shit.
