### ISSUE TITLE
If leaderboard is requested during update, it will fail as headers cannot be set after sent

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#152]
## Error in Place 2.0

**Error** in **routes/api.js:160**
Can't set headers after they are sent.

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/593fe7c1d3ab3e0018e0f3a7?event_id=593fe7c1d3ab3e0018e0f3a6&i=gh&m=ci)

## Stacktrace

    routes/api.js:160 - leaderboardManager.getInfo
    util/LeaderboardManager.js:52 - User.find.then.catch.err

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/593fe7c1d3ab3e0018e0f3a7?event_id=593fe7c1d3ab3e0018e0f3a6&i=gh&m=ci)

**Comment by AppleBetas** [comment]
lol fuck!

**Comment by nullpixel** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **routes/api.js:160**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/593fe7c1d3ab3e0018e0f3a7?event_id=59400087b8080e0019c77c97&i=gh&m=ra)
