### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by deadbaed** [dynasticdevelop/place#16]
it would be nice, so that way we can link stuff on twitter and other sites to get our logo to recognize the site

**Comment by AppleBetas** [comment]
bump

**Comment by tilda** [comment]
Possibly will be made but depending if I can get any ideas.

Also, what resolution?

**Comment by deadbaed** [comment]
the highest

**Comment by nullpixel** [comment]
Or an SVG

**Comment by nullpixel** [comment]
Done in https://github.com/dynasticdevelop/place/compare/80589df6a37e...1e1250cb2654
