### ISSUE TITLE
Simultaneous paint requests fail (util/PaintingManager.js:109)

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#163]
## Error in Place 2.0

**Error** in **util/PaintingManager.js:109**
Batch is already running

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/594c61d7eb386400189718be?event_id=594c61d7eb386400189718bd&i=gh&m=ci)

## Stacktrace

    util/PaintingManager.js:109 - addPixel
    models/user.js:215 - none

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/594c61d7eb386400189718be?event_id=594c61d7eb386400189718bd&i=gh&m=ci)

**Comment by AppleBetas** [comment]
Proposing #166 as a solution to this.
