### ISSUE TITLE
Improve performance with user load by revamping image generation

### ISSUE THREAD

**Issue by AppleBetas** [dynasticdevelop/place#166]
My current ideal implementation of this is as follows:
- [x] Image isn't regenerated every place, it regenerates every 30 seconds if it has been changed
- [x] When users get the canvas through API, it has a header with it. This header says the date and time it was last updated.
- [x] After loading the canvas, the client checks that header and sends a message through websockets saying "fetch_pixels" with that date and time.
- [x] The server sends those pixels changed as one huge "tile_placed" event in an array
- [x] Coalesce subsequent quick pixel updates into one socket event

This allows for minimal changes on the server, a decrease in the frequency of image updates, and a way for the client to keep up to date.

Any feedback on this would be greatly appreciated.

**Comment by deadbaed** [comment]
please don’t break my timelapses, thanks :)

отправлено с iPhone (простите если текст короткий)

**Comment by AppleBetas** [comment]
@ploctaux How often do you fetch the board image?

**Comment by deadbaed** [comment]
once every minute, using curl + url 

that’s it 

отправлено с iPhone (простите если текст короткий)

**Comment by AppleBetas** [comment]
You should be fine then. This just makes it so pixels in the image aren't immediately updated when someone places, but altogether at 30 second intervals if needed

**Comment by deadbaed** [comment]
awesome
