### ISSUE TITLE
Place Stability

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#174]
# Place 2.0 has almost matured enough to be called stable.

We are awaiting completion of #173, and #166. Progress can be tracked [here](https://github.com/dynasticdevelop/place/milestone/1)

## Stability rollout

Issues #173 and #166 will be merged into the `master` branch. Upon review, we will then roll these changes out to production. 

### What this means for you, the user

We can easily add modular functions, such as the ability for donator benefits. It'll create a whole new experience on Place. You can expect much less servers errors, and an all round better experience. 

### What this means for you, the developer

You can expect much more consistent code styles throughout the project, with guidelines being written.

### What this means for you, the self-hoster

You can now easily write or change functionality without changing the codebase.

# Branding

We're investigating as to if we should change the name, and domain of Place. We're happy to hear your suggestions, please drop them into our [discord](https://discord.gg/eD59FYA)

# FAQ
### What happened to the iOS app?

We're still working on it! It's getting there, however.

### Can I suggest more features that make the game more interesting?

Sure! We're not trying to be exactly like reddit. We'd love to implement a built in faction system, but we are not yet sure on how to do that.

**Comment by deadbaed** [comment]
what does it mean for timelapsers? lol

**Comment by nullpixel** [comment]
Nothing.

**Comment by AppleBetas** [comment]
Update: #166 is now merged

**Comment by nullpixel** [comment]
#173 is partially in master
