### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by deadbaed** [dynasticdevelop/place#178]
yes im that fucking annoying guy

wen eta translations

im down to do french

**Comment by AppleBetas** [comment]
@EricRabil could you work on making this possible from the technical side?

**Comment by EricRabil** [comment]
I can add the infrastructure, probably tonight

**Comment by deadbaed** [comment]
yo @EricRabil if you need some test strings i can provide them

**Comment by AppleBetas** [comment]
I'm gonna close this because we have a better issue at #183 setup to track this.

**Comment by deadbaed** [comment]
k no probs
