### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DreamPhreak** [dynasticdevelop/place#18]
Please have it so if I right-click on the canvas, it won't bring up the right-click menu, and especially won't place the tile I have in my hand. Also right now, right-clicking zooms in, but won't zoom back out. All of these features were in reddit's place.

**Comment by deadbaed** [comment]
that feature is planned

**Comment by toficofi** [comment]
Can be a quick fix 
`cameraController.oncontextmenu = (e) => e.preventDefault()`
