### ISSUE TITLE
Localization Tracker

### ISSUE THREAD

**Issue by EricRabil** [dynasticdevelop/place#183]
`root`
- [x] header
- [x] footer
- [x] admin_header
- [x] admin_footer

`public`
- [x] account
- [x] deactivated
- [x] force-pw-reset
- [x] guidelines
- [x] index
- [x] pick-username
- [x] popout
- [x] signin
- [x] signup

`public/views`
- [x] pixel_data
- [x] place
- [x] popout-container
- [x] social-buttons

`errors`
- [x] 404
- [x] 500

`admin`
- [x] actions
- [x] coming_soon
- [x] dashboard
- [x] similar_users_error
- [x] similar_users
- [x] users

**Comment by EricRabil** [comment]
For community guidelines, there will be a suffix on the guidelines file name which will follow i18n file formatting.

**Comment by deadbaed** [comment]
we already have a couple of languages ready, thanks @EricRabil for providing a quick solution!

**Comment by f-raZ0R** [comment]
All the checks are checked yet this isn't fixed???

**Comment by nullpixel** [comment]
Api isn’t done

**Comment by nullpixel** [comment]
on hold, we're rewriting client & backend.

**Comment by deadbaed** [comment]
sad!

**Comment by nullpixel** [comment]
it’s out of scope for now; we’ll reevaluate adding them at a later stage
