### ISSUE TITLE
Rename /api/pixel to /api/pos-info

### ISSUE THREAD

**Issue by AppleBetas** [dynasticdevelop/place#205]
As it turns out, some adblockers and anti-virus software like to block requests named `pixel`, as they mistake it for a tracking pixel. This, while annoying, isn't entirely unbeatable. Renaming this endpoint to `pos-info` would allow those with these terribly coded anti-virus and adblockers to get information about pixels.

**Comment by AppleBetas** [comment]
Fixed by fe569a6

**Comment by deadbaed** [comment]
that sucks, good think you saw that 👏
