### ISSUE TITLE
Show author of pixel

### ISSUE THREAD

**Issue by toficofi** [dynasticdevelop/place#23]
Feature request; hover over a pixel and see the author. 
It'd be cool if the pixel was highlighted with an outline to make it clearer which pixel that author is for.

**Comment by Bassofia** [comment]
I second this

**Comment by AppleBetas** [comment]
This feature is in progress

**Comment by deadbaed** [comment]
i third this

**Comment by nullpixel** [comment]
Done in some random commiy
