### ISSUE TITLE
Board size config does not work properly

### ISSUE THREAD

**Issue by kedarv** [dynasticdevelop/place#235]
If you change the board size to anything but 1400, users cannot place any tiles on the board. I'm not sure why this is happening, but if anyone has pointed to fix that would be appreciated!

edit: seems like boardSize must be > 1000?
edit2: that's not it..not sure where this error is being produced! no logs or anything either :(

**Comment by nullpixel** [comment]
This is intentional, and the config does not work as you’d think it does. If you have used place with more than one size, you will need to migrate the board — see inside scripts/.
Client logs would help me further.

**Comment by kedarv** [comment]
I"m confused then, what should the expected behavior be when I have an empty DB (first time launch of server) and boardSize = 700?

**Comment by nullpixel** [comment]
It should work. But you’ve not shown me any logs or errors, so I don’t have any idea what’s wrong

**Comment by nullpixel** [comment]
Closing, not seen any errors etc. Will reopen if you can provide additional info
