### ISSUE TITLE
When the cooldown goes off while zoomed in I can't place a pixel until I zoom out.

### ISSUE THREAD

**Issue by Bassofia** [dynasticdevelop/place#24]
1.- Place a pixel zoomed in.
2.- Wait for the cooldown (still zoomed in).
3.- Try to place another pixel when the cooldown goes off.

Expected result: Place the pixel
Actual result: No pixel placement.

How to place after that?

1.- Zoom out
2.- Place the pixel while zoomed out (Loss of precision)

Tried placing it after zooming out and in again but no success.

**Comment by toficofi** [comment]
I can't replicate this. Which browser? Do you get any errors in the developer's console?

**Comment by AppleBetas** [comment]
I doubt that the two are related because the client-side doesn't block you from posting in any other way, besides the overlay put over the colour picker, as the server-side knows to reject it.

Could you explain a bit more?

**Comment by Bassofia** [comment]
Google Chrome

Console dev;
place.js:6 socket successfully connected
place.js:6 socket successfully connected
place.js:6 socket successfully connected
https://place.dynastic.co/socket.io/?EIO=3&transport=polling&t=LivQNmB Failed to load resource: the server responded with a status of 503 ()
https://place.dynastic.co/socket.io/?EIO=3&transport=polling&t=LivQRgA Failed to load resource: the server responded with a status of 503 ()
https://place.dynastic.co/socket.io/?EIO=3&transport=polling&t=LivQTNZ Failed to load resource: the server responded with a status of 503 ()
place.js:6 socket successfully connected
https://place.dynastic.co/socket.io/?EIO=3&transport=polling&t=LivQVIE&sid=z2z634MQ2hVirs0LAADK Failed to load resource: the server responded with a status of 503 ()
place.js:5 socket error: Error: xhr poll error
place.js:6 socket successfully connected
place.js:6 socket successfully connected
Failed to create temp file 18 : It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources.

**Comment by Bassofia** [comment]
Apparently works now. Closing
