### ISSUE TITLE
Comply with GDPR

### ISSUE THREAD

**Issue by AppleBetas** [dynasticdevelop/place#247]
- [x] Allow users to fully delete accounts from servers
   * 7 day deletion period
   * if a user logs in during that time, deletion is cancelled 
- [x] Hash all stored IPs (with new absence of readable IPs, could implement software IP ban for hashes to replace CF being used for it)
- [x] Cookie banner for Google Analytics
- [x] Allow users to download a copy of all data we have on them (basically nothing)

**Comment by deadbaed** [comment]
cookies banners: here some project that you might like:
* https://github.com/rapidwebltd/basic-js-cookie-banner
* https://github.com/Alex-D/Cookies-EU-banner
* https://github.com/rapidwebltd/basic-js-cookie-banner (i dont like this one that much)

**Comment by deadbaed** [comment]
> - [ ] Cookie banner for Google Analytics

i saw that you use npm for the project, so i found this: https://alex-d.github.io/Cookies-EU-banner/

looks simple to add, what do you think @nullpixel @AppleBetas ?

**Comment by AppleBetas** [comment]
We’re likely going to make our own, @x4m3. It’s such a simple thing that it doesn’t make much sense to use a library and introduce a mixmatch of styles

**Comment by AppleBetas** [comment]
@x4m3 actually ended up using that with custom CSS

**Comment by deadbaed** [comment]
horray! congrats @nullpixel @AppleBetas :1st_place_medal:
