### ISSUE TITLE
Tab randomly crashes after a period of time

### ISSUE THREAD

**Issue by EricRabil** [dynasticdevelop/place#250]
No diagnostics have been run. More information is needed at this time; until then, there is nothing we can do.

If you meet any of the following criteria,
- Have any crash logs
- Have experienced this bug
- Have any knowledge about this bug

Please comment what information you can provide.

**Comment by deadbaed** [comment]
i have experienced this bug, i place a pixel on the canvas, go to other tabs for some time, come back to the canvas.place tab, and right after i can hear my fan spin up a lot, i try to place a pixel, and chrome tells me that the tab is not responding. killing the tab and opening a new one for canvas.place fixes the issue.
reloading the tab does not fix it. i tried that a bunch of times with no success.

**Comment by EricRabil** [comment]
[Heaps.zip](https://github.com/dynastic/place/files/2066571/Heaps.zip)
Memory allocation heaps collected on Place

**Comment by EricRabil** [comment]
This is likely being caused by an external library, from what I see in the heaps it's either Raven or Interact.JS (albeit I don't really know how to read a heap, I'm going out on a limb here.)

**Comment by EricRabil** [comment]
The breakpoint at the point of OOM crash is at `socket.js:60`

**Comment by AppleBetas** [comment]
Go Eric!

**Comment by AppleBetas** [comment]
Caused by socket code. 

When the socket connection failed, all sent events are added to a queue. When the socket re-opens, this queue is sent using the same function that added them to a queue. If in the rare case (which happens for us), the socket is not connected when this queue is used, it will create an infinite loop (usually of "identify" events).

**Comment by AppleBetas** [comment]
Issue will be re-opened if the fix does not work.

**Comment by AppleBetas** [comment]
Users haven't experienced problems in a while, seems to be resolved.
