### ISSUE TITLE
Usernames are case-sensitive

### ISSUE THREAD

**Issue by Mstrodl** [dynasticdevelop/place#41]
`username.toLowerCase()` pls kthxbai

**Comment by AppleBetas** [comment]
This would be better solved by changing code in two places: username verification and sign in should check insensitively for other people with the same name, to preserve the original casing the account was created with.

**Comment by ctian1** [comment]
Why would you need to check on sign in? You should just check when the username record is inserted w/ mongoose

**Comment by nullpixel** [comment]
Could be implemented like we currently do username regex checks

**Comment by AppleBetas** [comment]
@pangeacake I meant that the username record should be searched case insensitively.
