### ISSUE TITLE
lwip fails with node v7 latest

### ISSUE THREAD

**Issue by tilda** [dynasticdevelop/place#58]
Fixed this problem by switching to `pajk-lwip`.

However, this problem deserves a issue anyways. `lwip` has old libs, which cause it to fail the build. The new package seems to output a bunch of warnings but it's at least working. 

Found the new package from here: https://github.com/EyalAr/lwip/pull/258#issuecomment-281689203

**Comment by nullpixel** [comment]
Yeah. We currently only support node v7.4 due to this.

If you wish to open a PR for this please do, if not, I'll likely switch deps and close this when I get time

**Comment by tilda** [comment]
Will do.

**Comment by nullpixel** [comment]
Fixed in #59

**Comment by ghost** [comment]
The build stills fails for me on node -v v7.9.0

**Comment by tilda** [comment]
Are you on the latest revision? Do a quick `git pull`

**Comment by ghost** [comment]
Just did that,

Found out that's it a build error, Might be something with my install, If you want to help here's the error in question.

`png.obj : error LNK2001: unresolved external symbol png_save_uint_32 [C:\Users\Deanna\Desktop\massive
legobot\place\node_modules\pajk-lwip\build\lwip_decoder.vcxproj]
C:\Users\Deanna\Desktop\massivelegobot\place\node_modules\pajk-lwip\build\Release\lwip_decoder.node :
 fatal error LNK1120: 1 unresolved externals [C:\Users\Deanna\Desktop\massivelegobot\place\node_modul
es\pajk-lwip\build\lwip_decoder.vcxproj]`

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-
gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\
node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Deanna\Desktop\massivelegobot\place\node_modules\pajk-lwip
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN place@1.0.0 No repository field.
npm WARN place@1.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin
\\npm-cli.js" "i"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! pajk-lwip@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pajk-lwip@0.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pajk-lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pajk-lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pajk-lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Deanna\AppData\Roaming\npm-cache\_logs\2017-04-27T22_42_02_388Z-debug.log

**Comment by AppleBetas** [comment]
I'm locking this issue because it isn't relevant to the Place project. Any more questions or inquiries for help should be directed to the [Pajk/lwip](https://www.github.com/Pajk/lwip) fork, or the original [EyalAr/lwip](https://www.github.com/EyalAr/lwip) project.
