### ISSUE TITLE
"official mods" from different communities

### ISSUE THREAD

**Issue by deadbaed** [dynasticdevelop/place#6]
like one from r/france, one from r/linux, r/placestart and so on

**Comment by Bassofia** [comment]
That's being done at the "Reddit world congress (Discord and subreddit)", I think for now that should be kept there and this place should only focus in the actual "game"

**Comment by deadbaed** [comment]
@Bassofia that's clever, i didn't think of that .

thanks to remind me that

**Comment by deadbaed** [comment]
closing this, open it again if you need to
