### ISSUE TITLE
Feature request: Steemconnect authentication

### ISSUE THREAD

**Issue by grctest** [dynasticdevelop/place#64]
Hey,

Would it be possible to add Steemconnect authentication?

https://steemconnect.com/
https://steemit.com/tutorial/@krnel/tutorial-how-to-add-steemit-login-to-your-site-with-steemconnect

I'm very interested in running my own place instance.

Thanks for the great work 👍

**Comment by nullpixel** [comment]
I'll look into it!

**Comment by AppleBetas** [comment]
At the moment, we will not be adding this feature.

**Comment by grctest** [comment]
> At the moment, we will not be adding this feature.

Would I be able to donate some Bitcoin/Steem/GRC in return for this feature?

**Comment by nullpixel** [comment]
Unfortunately, after looking over the docs, it seems pretty time consuming to add, we're not in a situation with a lot of free time.

I will be happy to _try_ to do this for you, but no guarantees that it'll be soon.

**Comment by grctest** [comment]
Looks like someone's implemented a Steem place now: https://steemit.com/steemdev/@steempixels/steempixels-com-the-world-s-first-blockchain-powered-decentralized-collaborative-pixel-canvas
