### ISSUE TITLE
make a timelapse system

### ISSUE THREAD

**Issue by deadbaed** [dynasticdevelop/place#7]
i can host the archives if you want

**Comment by AppleBetas** [comment]
+1

**Comment by itsmehemant123** [comment]
👍🏻

**Comment by deadbaed** [comment]
i made it!

first timelapse available here: https://youtu.be/H5r5NT7fAn8
pics are available here: https://disk.ph1l3r.fr/place20/img/

**psa: no need to make a timelapse system, it has already been made** (unless you wanna have fun in that case go ahead)

**Comment by deadbaed** [comment]
is it safe to close this one? @AppleBetas

**Comment by AppleBetas** [comment]
Yep
