### ISSUE TITLE
Cannot click to view tile information

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#78]
This bug was introduced with #73, by @EricRabil.

Due to the new behaviour, whilst a user is on cooldown, they can no longer view tile information. I'd consider this a huge lack of functionality, and I would want to address this as soon as I can.

However, particularly for mobile users, this could be challenging to implement, so we'll need to hold a discussion regarding this at some point today.

---
Relevant reddit thread https://www.reddit.com/r/place20/comments/676rfd/annoying_bug_any_workaround/

**Comment by AppleBetas** [comment]
Fixing
