### ISSUE TITLE
Sorting the date joined in ModTools is horribly inaccurate

### ISSUE THREAD

**Issue by EricRabil** [dynasticdevelop/place#86]
When sorting ascending/descending the account created column in mod tools, the results do not correspond and are in a seemingly random order.

**Comment by AppleBetas** [comment]
Not able to reproduce this

**Comment by EricRabil** [comment]
Sec!

**Comment by AppleBetas** [comment]
Turns out this bug does not actually exist, but is caused by the placement of the sorting indicator. It would be appreciated if you could open a separate issue or just PR fix for this
